export const departments = [
    'Antioquia', 'Bolivar', 'Valle', 'Cundinamarca', 'Santander'
];

export const products = [
    {
      id: '1',
      name: 'Estuche del Galaxy Ultra',
      price: 40.0,
      description: 'Protege tu Galaxy Ultra con estilo y seguridad con este estuche premium.',
      image: require('../assets/ProductosCelucos/Estuchegalaxy.png'),
      categoria: 'Celulares',
      favorite: true,
    },
    {
      id: '2',
      name: 'Galaxy 23 Ultra',
      price: 3200.0,
      description: 'El smartphone más avanzado de Samsung, con cámara de alta resolución y rendimiento ultra rápido.',
      image: require('../assets/ProductosCelucos/galaxy23ultra.png'),
      categoria: 'Celulares',
      favorite: false,
      
    },
    {
      id: '3',
      name: 'Iphone 15',
      price: 3000.0,
      discountedPrice: 3000.0 * 0.9,
      description: 'Descubre la nueva generación del iPhone con su diseño elegante y potente tecnología.',
      image: require('../assets/ProductosCelucos/iphone15.png'),
      categoria: 'Celulares',
      favorite: true,
      available: true,
    },
    {
      id: '4',
      name: 'Asus 14',
      price: 2400.0,
      description: 'Laptop compacta y eficiente, ideal para el trabajo y el entretenimiento diario.',
      image: require('../assets/ProductosComp/asus14.png'),
      categoria: 'Computadores',
      favorite: true,
      available: true,
    },
    {
      id: '5',
      name: 'Computador Gaming',
      price: 5000.0,
      discountedPrice: 5000.0 * 0.65,
      description: 'Máquina de alto rendimiento para los gamers más exigentes, con gráficos y velocidad excepcionales.',
      image: require('../assets/ProductosComp/compugaming.png'),
      categoria: 'Computadores',
      favorite: true,
    },
    {
      id: '6',
      name: 'Ideapad 5',
      price: 1900.0,
      description: 'Laptop versátil con un diseño delgado y batería de larga duración.',
      image: require('../assets/ProductosComp/Ideapad-5.png'),
      categoria: 'Computadores',
    },
    {
      id: '7',
      name: 'Balón de Baloncesto',
      price: 120.0,
      discountedPrice: 120.0 * 0.8,
      description: 'Balón oficial de baloncesto, perfecto para competiciones y entrenamientos.',
      image: require('../assets/ProductosDeportes/balon-baloncesto-oficial.png'),
      categoria: 'Deportes',
      favorite: true,
      available: true,
    },
    {
      id: '8',
      name: 'Balón de Fútbol',
      price: 200.0,
      description: 'Balón de fútbol de alta calidad, diseñado para un rendimiento óptimo en el campo.',
      image: require('../assets/ProductosDeportes/balon-futbol.png'),
      categoria: 'Deportes',
    },
    {
      id: '9',
      name: 'Camisa de la Cabra',
      price: 9000.0,
      discountedPrice: 9000.0 * 0.4,
      description: 'Edición limitada de la camisa inspirada en el icónico "GOAT" del deporte.',
      image: require('../assets/ProductosDeportes/camisathegoat.png'),
      categoria: 'Deportes',
    },
    {
      id: '10',
      name: 'Cama',
      price: 2100.0,
      discountedPrice: 2100.0 * 0.8,
      description: 'Cama cómoda y moderna para un descanso placentero.',
      image: require('../assets/ProductosHogar/cama.png'),
      categoria: 'AccesoriosDeCasa',
    },
    {
      id: '11',
      name: 'Comedor',
      price: 1300.0,
      description: 'Juego de comedor elegante y funcional para cualquier hogar.',
      image: require('../assets/ProductosHogar/comedor.png'),
      categoria: 'AccesoriosDeCasa',
    },
    {
      id: '12',
      name: 'Lámpara de Noche',
      price: 600.0,
      discountedPrice: 600.0 * 0.95,
      description: 'Lámpara de mesa con un diseño moderno, ideal para iluminar cualquier espacio.',
      image: require('../assets/ProductosHogar/lampara-de-mesa.png'),
      categoria: 'AccesoriosDeCasa',
    },
    {
      id: '13',
      name: 'Play 5',
      price: 2600.0,
      description: 'La consola de videojuegos más avanzada de Sony, con gráficos impresionantes y un rendimiento superior.',
      image: require('../assets/ProductosConsolas/play-5.png'),
      categoria: 'Games',
    },
    {
      id: '14',
      name: 'Play 2',
      price: 400.0,
      discountedPrice: 400.0 * 0.5, 
      description: 'Consola retro de Sony, perfecta para los amantes de los juegos clásicos.',
      image: require('../assets/ProductosConsolas/play-2.png'),
      categoria: 'Games',
    },
    {
      id: '15',
      name: 'Xbox 360',
      price: 550.0,
      discountedPrice: 550.0 * 0.75, 
      description: 'La clásica consola de Microsoft, conocida por su catálogo de juegos y rendimiento.',
      image: require('../assets/ProductosConsolas/xbox-360.png'),
      categoria: 'Games',
    },
  ];
  
  export const productsPaymentBranch = [
    {
      id: '1',
      image: 'https://cdn-icons-png.flaticon.com/512/1312/1312307.png',
      description: 'Producto 1 de alta calidad',
      value: 1000,
    },
    {
      id: '2',
      image: 'https://cdn-icons-png.flaticon.com/512/1312/1312307.png',
      description: 'Producto 2 de alta calidad',
      value: 2000,
    },
    {
      id: '3',
      image: 'https://cdn-icons-png.flaticon.com/512/1312/1312307.png',
      description: 'Producto 2 de alta calidad',
      value: 2000,
    },
  ];
  

 export const menuItems = [
    { name: 'Ofertas', screen: 'Offers' },
    { name: 'Categorías de artículos', screen: 'Categories' },
    { name: 'Sucursal de pago', screen: 'PaymentBranch' },
    { name: 'Ayuda y Soporte', screen: 'HelpSupport' },
  ];